---
title: "Evening Exercise on Partials"
type: "challenge"
description: "Improve the code quality of the Movie Shack Hut webapp."
visibility: "assign"
tags: "evening-exercise, rails, partials"
ignore:
- "evening-exercise-partials.md"
